### ISSUE TITLE
[BUG] 85652 - на старте не был передан конфиг частично или полностью

### ISSUE THREAD

**Issue by Karloid** [MailRuChamps/miniaicups#58]
http://aicups.ru/session/85652/ 
у себя в отладочном вызове что GAME_WIDTH не нашелся в первом конфиге и либа кинула exception.
У двух других игроков судя по всему была похожая проблема, а у одного все ок.

```
Exception in thread "main" org.json.JSONException: JSONObject["GAME_WIDTH"] not found.
	at org.json.JSONObject.get(JSONObject.java:520)
	at org.json.JSONObject.getInt(JSONObject.java:694)
	at Game.<init>(Game.java:24)
	at Game.from(Game.java:39)
	at Main.main(Main.java:33)

app.bundle.js?v=1.3.4:45494 Tick[3] Ожидание ответа превышено!
app.bundle.js?v=1.3.4:45494 Tick[4] Решение отключилось от механики до окончания!
```

**Comment by tongohiti** [comment]
Смутно похоже на какие-то проблемы с буферизацией ввода-вывода. У своей стратегии обнаружил такое:
`````
2018/03/30 06:27:55 Error unmarshalling JSON invalid character 'X' after top-level value
2018/03/30 06:27:55 \",\"X\":659,\"Y\":860},{\"T\":\"F\",\"X\":717,\"Y\":846},{\"T\":\"F\",\"X\":806,\"Y\":911},{\"T\":\"F\",\"X\":699,\"Y\":935},{\"T\":\"F\",\"X\":652,\"Y\":887},{\"T\":\"F\",\"X\":531,\"Y\":835},{\"T\":\"F\",\"X\":709,\"Y\":809}, /* дальше обрезал для краткости */
`````
(Игра №85820, жёлтый игрок).
То есть в стратегию пришёл JSON обрезаный посередине. Локально таких проблем с данной стратегией не наблюдается.

**Comment by BorisKolganov** [comment]
После фиксов серверного кода данная проблема должна уйти
